### ISSUE TITLE
Question about one signal configuration

### ISSUE THREAD

**Issue by kwstasna** [parse-server-modules/parse-server-onesignal-push-adapter#10]
Hello and very nice work with the adapter guys!

I have one question, if i put the adapter at my parse-server app, can i send push notifications from the onesignal.com dashboard? Or only from cloud code?
Thanks!

**Comment by gdeglin** [comment]
Yes and no.

OneSignal will not be aware of which devices are subscribed to notifications until you send at least one notification to the device via Cloud Code. Once OneSignal is aware of the device then you can send notifications to it and your other subscribed devices through the OneSignal dashboard.

In general the dashboard will work better for you if you include the OneSignal SDK in your app. This will remove the above requirement, and you will still be able to send notifications through the OneSignal Parse Server adapter too

**Comment by Onwa1kenobi** [comment]
How about sending from the parse-dashboard?
I tried it, sometimes it works, sometimes it doesn't. I have no idea what the problem might be.
