### ISSUE TITLE
Error sending push: could not find sender

### ISSUE THREAD

**Issue by mymanga** [parse-server-modules/parse-server-onesignal-push-adapter#11]
I get the following message when i try to send a push message
```
verb parse-server-push-adapter Can not find sender for push type android, [object Object]
5/12/2016 3:06:19 AM[36mverbose[39m: sent push! 0 success, 0 failures
```

**Comment by flovilmart** [comment]
This is unrelated to the one signal push adapter, but on the https://github.com/parseplaform/parse-server-modules/parse-server-push-adapter
