### ISSUE TITLE
Not work on android

### ISSUE THREAD

**Issue by MattiaConfalonieri** [parse-server-modules/parse-server-onesignal-push-adapter#13]
The adapter work well for iOS recipients but not seem to work with the android... anybody have the same problem?

**Comment by gdeglin** [comment]
Android support requires the OneSignal SDK to be added to your app. This is because each notificaiton service has it's own notification payload format, and OneSignal's payload format can only be understood by the OneSignal SDK.

**Comment by AlternativeIndustries** [comment]
No they activate me an option to bypass onesignal custom play load. That on iOS work well but android device still not receive push notification.

**Comment by MattiaConfalonieri** [comment]
@gdeglin you right, the problem is that for Android OneSignal adapter need OneSignal sdk installed.
