### ISSUE TITLE
deviceToken is Empty - Installation class

### ISSUE THREAD

**Issue by tizkka** [parse-server-modules/parse-server-onesignal-push-adapter#14]
We are trying to set the `deviceToken` (Android app) in Installation class so then we can send push notifications using OneSignal as follows:

ParseInstallation installation = ParseInstallation.getCurrentInstallation();
      installation.put("GCMSenderId",senderId);
      installation.put("pushType","gcm");
      installation.put("deviceToken",token);

Once we try to save, we get an exception: 
Cannot modify `deviceToken` property of an _Installation object. android

Any advice on how/where to set the "deviceToken" in Installation class?

**Comment by faladinojames** [comment]
Yeah. Same here. Device token is empty pushes are not delivered

**Comment by faladinojames** [comment]
The deviceToken will be set automatically by parse-server. The issue I had was that I was changing the serverURL of my app between the localURL and the online server. All I did was to uninstall the app and install the new one and it started working.

**Comment by flovilmart** [comment]
This is unrelated to this adapter, please open on parse-server or on the Android-SDK repository
