### ISSUE TITLE
android_background_data flag is missing

### ISSUE THREAD

**Issue by lolobosse** [parse-server-modules/parse-server-onesignal-push-adapter#3]
Hey,

I do not how far you want to go in the implementation but I think for people who already had a really advanced Android app, this `android_background_data` flag is the only one which can be used to have the [Background Data](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-silent-notifications) and it is really useful to bring the notifications to another level.

I'll try to do a short PR if I success implementing it

**Comment by flovilmart** [comment]
Fixed by #6
