### ISSUE TITLE
broken on Parse-Server 2.3.3

### ISSUE THREAD

**Issue by jjdp** [parse-server-modules/parse-server-onesignal-push-adapter#33]
caused by https://github.com/ParsePlatform/parse-server/pull/3080.
deviceToken is not being sent

**Comment by flovilmart** [comment]
Can you provide more informations please? The changes on Parse-server were not supposed to affect adapters

**Comment by jjdp** [comment]
when i push in the cloud it returns a promise resolved to true but I noticed on my one signal dashboard a new user is added without a device. Before this would not create a new one, < v2.3.3. The device and platform will be empty, subscribed will be set to "no" and not like the picture shown

![one signal](https://cloud.githubusercontent.com/assets/5244520/22930570/e1115d10-f2fb-11e6-9209-ba9a161164a1.png)

 I can't reproduce again since I have downgraded back to 2.3.2 but I will be happy to help. 

Im guessing the deviceToken is not being returned in `post['include_android_reg_ids'].push(i['deviceToken'])`.

I do not know about IOS yet since I have only tested it on android.

**Comment by jjdp** [comment]
i forked the repo and updated some stuff to change it to sending the playerID instead of the deviceToken. the catch is that you have to get the playerID on the client using their provided SDKs, which is fine in my case of the project. 

it's not 2.3.3's fault, something changed in one signal's REST api
