### ISSUE TITLE
How do I install these files?

### ISSUE THREAD

**Issue by D34thStalker** [parse-server-modules/parse-server-onesignal-push-adapter#5]
I am trying to deploy this adapter into my Parse Server that is going into AWS EB. If I download this adapter. Where exactly do I put these files? And which ones?? I have tried putting them in the node_modules folder but AWS says its not finding the files.

**Comment by robtaireeo** [comment]
Add parse-server-onesignal-push-adapter to your package.json, then in your app.js/index.js file add:

```
var oneSignalPushAdapter = new OneSignalPushAdapter({
    oneSignalAppId: id,
    oneSignalApiKey: key'
});

var api = new ParseServer({
    databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
    ...
    push: {
        adapter: oneSignalPushAdapter
    },
    ...
});
```
